baseURL = "https://fukushi-note.com/"
languageCode = "ja"
title = "ふくしノート"
buildFuture = true

[params]
  description = "障害福祉サービスの指定申請を支援する行政書士であり、自らも障害福祉サービス・介護保険サービスの事業所を経営する経営者でもある視点から、開業から運営までの実務を解説するブログ。"
  author = "ぺーさん"

[permalinks]
  posts = "/blog/:slug/"

[outputs]
  home = ["HTML", "RSS"]
