baseURL = "https://fukushi-note.com/"
languageCode = "ja"
title = "ふくしノート"
buildFuture = true

[params]
  description = "訪問系障害福祉サービス（居宅介護・重度訪問介護・同行援護・行動援護）の指定申請と運営を、指定申請を支援する行政書士であり、自らも訪問介護事業所を経営する経営者でもある視点から解説するブログ。"
  author = "ぺーさん"

[permalinks]
  posts = "/blog/:slug/"

[outputs]
  home = ["HTML", "RSS"]
